services:
  ghost:
    image: ghost:6-alpine
    container_name: ghost
    restart: unless-stopped
    ports:
      - "${GHOST_PORT:-2368}:2368"
    environment:
      url: ${GHOST_URL:-http://localhost:2368}
      database__client: sqlite3
      database__connection__filename: /var/lib/ghost/content/data/ghost.db
      NODE_ENV: development
    volumes:
      - /contents:/var/lib/ghost/content
    networks:
      - ghost

networks:
  ghost:
