apiVersion: v1
kind: Service
metadata:
  name: juicefs-gateway
  labels:
    app: juicefs-gateway
spec:
  type: LoadBalancer
  ports:
    - port: 9002
      targetPort: 9000
      name: s3
  selector:
    app: juicefs-gateway
